- hosts: all
  name: Test command
  gather_facts: false
  any_errors_fatal: "{{ fatal }}"
#  any_errors_fatal: true
#  any_errors_fatal: false
#  max_fail_percentage: 0
  vars:
    fatal: false
  tasks:
    - debug:
        msg: Fatal is set to "{{ fatal }}"

    - command: /bin/false
      when: inventory_hostname == 'master-3.s000005.slurm.io'

    - debug:
        msg: I still run on other hosts
